version: '2'
services:
  varnish:
    # keopx/varnish available tags: latest, 4.0.
    container_name: reciprocity_varnish
    image: keopx/varnish:4.0
    ports:
      - "10081:80"
      - "10082:6082"
    volumes:
      - ./config/varnish/default.vcl:/etc/varnish/default.vcl
      ## mattiasgeniar file: https://github.com/mattiasgeniar/varnish-4.0-configuration-templates
      # - ./config/varnish/drupal-template.vcl:/etc/varnish/default.vcl
      ## Niteman file: https://github.com/NITEMAN/varnish-bites/blob/master/varnish4/drupal-base.vcl
      # - ./config/varnish/drupal-base.vcl:/etc/varnish/default.vcl
    # environment:
      # - VARNISH_PORT=80
      # - VARNISH_MEMORY=500M
      # Next values only works with default default.vcl file.
      # - VARNISH_BACKEND_IP=web
      # - VARNISH_BACKEND_PORT=80
    links:
      - web
  web:
    container_name: reciprocity_web
    # keopx/apache-php available tags: latest, 7.1, 7.0, 5.6.
    image: keopx/apache-php:7.1
    ports:
      # 8008 works without varnish.
      - "10083:80"
      # - "443:443"
    links:
      - mysql
      - redis
      - mail
      - drush
      - composer
    volumes:
      - ./data/www:/var/www # Data.
      - ./config/vhosts:/etc/apache2/sites-enabled
      ### See: https://github.com/keopx/docker-lamp for more information.
      ## php.ini for php 7.x and remove environment varibles.
      - ./config/php/5.6/php.ini:/etc/php/5.6/apache2/php.ini
      ## Opcache for php 7.0
      # - ./config/php/opcache-recommended.ini:/etc/php/7.0/apache2/conf.d/10-opcache.ini
      ## APCU for php 7.0
      # - ./config/php/apcu.ini:/etc/php/7.0/apache2/conf.d/20-apcu.ini
      ## Xdebug for php 7.0
      # - ./config/php/xdebug.ini:/etc/php/7.0/apache2/conf.d/20-xdebug.ini
      ## Xhprof for php 7.0
      #- ./config/php/xhprof.ini:/etc/php/7.0/apache2/conf.d/20-xhprof.ini
      ## Drush aliases support. e.g.
      # - ~/.drush:/root/.drush
      ## SSH support. e.g.
      # - ~/.ssh:/root/.ssh
    # environment:
      ### WARNING: Use only if you not use custom php.ini.
      ## ssmtp mail sender.
      # - PHP_SENDMAIL_PATH="/usr/sbin/ssmtp -t"
      ## SMTP server configruation: "domain:port" | "mail" server domain is mailhog container_name.
      # - PHP_SENDMAIL_DOMAIN=mail:1025
    working_dir: /var/www
  mysql:
    container_name: reciprocity_mysql
    # keopx/mysql available tags: latest, 8.0, 5.7, 5.6, 5.5.
    image: keopx/mysql:5.5
    ports:
      - "10084:3306"
    volumes:
      - ./data/database:/var/lib/mysql
      ## Custom setup for MySQL
      # - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=reciprocity
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
  redis:
    container_name: reciprocity_redis
    # keopx/redis available tags: latest, 3.2, 3.0
    image: keopx/redis:3.2
    ports:
      - "10085:6379"
  phpmyadmin:
    container_name: reciprocity_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "10086:80"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
  mail:
    container_name: reciprocity_mail
    image: mailhog/mailhog
    ports:
      - "10087:8025"
      - "10088:1025"
  composer:
    container_name: reciprocity_composer
    restart: 'no'
    image: composer/composer:php7
    command: install 
  drush:
    container_name: reciprocity_drush
    image: drush/drush
